Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

**Q1.** Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list, and the variable array_list is a NumPy array. 

In Python lists, the elements can have different data types,

 while NumPy arrays have a homogeneous data type, meaning all elements in the array have the same data type.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'list'>
Data type of array_list: <U1


**Q2.** Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Data type of each element in the Python list
print("Data types of elements in list_:")
for elem in list_:
    print(type(elem))

# Data type of each element in the NumPy array
print("\nData types of elements in array_list:")
for elem in array_list:
    print(elem.dtype)


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<U1
<U1
<U1
<U1
<U1


**Q3.** Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? 

If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list after the change.

When you create the NumPy array array_list with the dtype=int parameter, it explicitly converts the elements of the Python list list_ to integers.

This means that the elements of the NumPy array will have the data type int, while the elements of the original Python list will remain as strings.

In [5]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Data type of each element in the Python list
print("Data types of elements in list_:")
for elem in list_:
    print(type(elem))

# Data type of each element in the NumPy array
print("\nData types of elements in array_list:")
for elem in array_list:
    print(type(elem))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


**Q4.** Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [6]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [9]:
shape = num_array.shape
print("Shape of num_array:", shape)

size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
arr_zeros = np.zeros((3,3))

print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6.** Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
arr_identity = np.identity((5))

print(arr_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
